config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= blog.description %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.slim
=render partial:"blogs/layouts/header" 

=render partial:"blogs/layouts/banner" 

=render partial:"blogs/layouts/projects" 

=render partial:"blogs/layouts/about"

=render partial:"blogs/layouts/contact"

=render partial:"blogs/layouts/footer"
        

app/views/blogs/layouts/_about.html.slim
.arc-about.arc-section-spacing#arc-about
    .arc-container
        .arc-section-header
            h2.section-heading.arc-fs-xl About
            .section-description.arc-pt-4
                p orem ipsum dolor sit amet, consectetur adipiscing elit, sed 
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris 
                  nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat 
                  cupidatat non proident, sunt in culpa qui officia deserunt mollit 
                  anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor
                  incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
                  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 
                  consequat.
        .arc-designers-list
            .arc-row
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-designer-card.arc-mt-6.arc-bg-white
                        .arc-image-section
                            img.arc-img-cover src="https://www.w3schools.com/w3images/team2.jpg"
                        .arc-card-content
                            h3.arc-fs-xl.arc-pt-2 John Doe
                            span.arc-pt-3 CEO & Founder
                            p.arc-pt-3 Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                            button.arc-btn-primary.arc-btn-fluid.arc-mt-3 Contact
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-designer-card.arc-mt-6.arc-bg-white
                        .arc-image-section
                            img.arc-img-cover src="https://www.w3schools.com/w3images/team1.jpg"
                        .arc-card-content
                            h3.arc-fs-xl.arc-pt-2 Jane Doe
                            span.arc-pt-3 Designer
                            p.arc-pt-3 Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                            button.arc-btn-primary.arc-btn-fluid.arc-mt-3 Contact  
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-designer-card.arc-mt-6.arc-bg-white
                        .arc-image-section
                            img.arc-img-cover src="https://www.w3schools.com/w3images/team3.jpg"
                        .arc-card-content
                            h3.arc-fs-xl.arc-pt-2 Mike Ross
                            span.arc-pt-3 Architect
                            p.arc-pt-3 Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                            button.arc-btn-primary.arc-btn-fluid.arc-mt-3 Contact  
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-designer-card.arc-mt-6.arc-bg-white
                        .arc-image-section
                            img.arc-img-cover src="https://www.w3schools.com/w3images/team4.jpg"
                        .arc-card-content
                            h3.arc-fs-xl.arc-pt-2 Dan Star
                            span.arc-pt-3 Architect
                            p.arc-pt-3 Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                            button.arc-btn-primary.arc-btn-fluid.arc-mt-3 Contact                                            

app/views/blogs/layouts/_banner.html.slim
.arc-hero.arc-position-relative#arc-hero
    .arc-hero-image.arc-overlay
        img.hero-img src="https://www.w3schools.com/w3images/architect.jpg"
    .arc-hero-text.arc-position-absolute
        h1 
            span.hero-text-large BR
            span.hero-text-small Architects

app/views/blogs/layouts/_contact.html.slim
.arc-contact.arc-section-spacing.arc-pb-0#arc-contact
    .arc-container
        .arc-section-header
            h2.arc-section-heading.arc-flex.arc-fs-xl 
                | Contact
                .arc-tool-tip.arc-ml-1
            .section-description.arc-pt-4
                p Lets get in touch and talk about your next project.
        .arc-form.arc-pt-4
            form.arc-contact-form
                input.arc-mt-4.arc-p-2 type="text" placeholder="Email"
                input.arc-mt-4.arc-p-2 type="text" placeholder="Subject"
                textarea.arc-mt-4.arc-p-2 cols="2" rows="2" placeholder="Comment"
                button.arc-btn-primary.arc-btn-bg-black.arc-mt-4 Send Message

        

app/views/blogs/layouts/_footer.html.slim
.arc-footer.arc-text-center
    .contact-image
        img.arc-img-cover src="https://www.w3schools.com/w3images/map.jpg"
    p.arc-p-7 
        | Powered By &nbsp;
        a W3.css
        = 

script src="https://code.jquery.com/jquery-3.6.0.min.js"  
script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"

script src="blogs/assets/js/jquery.js"

app/views/blogs/layouts/_header.html.slim
.arc-header.arc-position-fixed
  .arc-container-fluid.arc-flex.arc-justify-content-between.arc-align-items-center
    .arc-branding
      a 
        b BR
        | Architects
    .arc-menu
      ul.arc-flex
        li: a(href='#arc-projects') Projects
        li: a(href='#arc-about') About
        li: a(href='#arc-contact') Contact

app/views/blogs/layouts/_projects.html.slim
.arc-projects.arc-section-spacing#arc-projects
    .arc-container
        .arc-section-header
            h2.section-heading.arc-fs-xl Projects
        .arc-projects-lists.arc-pt-8
            .arc-row
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-project.arc-position-relative.arc-mt-4
                        .arc-project-tag.arc-position-absolute Summer House
                        .arc-image-section.arc-overlay
                            img.arc-img-cover src="https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-project.arc-position-relative.arc-mt-4
                        .arc-project-tag.arc-position-absolute Brick House
                        .arc-image-section.arc-overlay
                            img.arc-img-cover src="https://www.w3schools.com/w3images/house2.jpg"
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-project.arc-position-relative.arc-mt-4
                        .arc-project-tag.arc-position-absolute Renovated
                        .arc-image-section.arc-overlay
                            img.arc-img-cover src="https://www.w3schools.com/w3images/house3.jpg"
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-project.arc-position-relative.arc-mt-4
                        .arc-project-tag.arc-position-absolute Barn House
                        .arc-image-section.arc-overlay
                            img.arc-img-cover src="https://www.w3schools.com/w3images/house4.jpg"
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-project.arc-position-relative.arc-mt-4
                        .arc-project-tag.arc-position-absolute Summer House
                        .arc-image-section.arc-overlay
                            img.arc-img-cover src="https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-project.arc-position-relative.arc-mt-4
                        .arc-project-tag.arc-position-absolute Brick House
                        .arc-image-section.arc-overlay
                            img.arc-img-cover src="https://www.w3schools.com/w3images/house5.jpg"
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-project.arc-position-relative.arc-mt-4
                        .arc-project-tag.arc-position-absolute Renovated
                        .arc-image-section.arc-overlay
                            img.arc-img-cover src="https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
                .arc-col.arc-col-sm-6.arc-col-md-3
                    .arc-project.arc-position-relative.arc-mt-4
                        .arc-project-tag.arc-position-absolute Barn House
                        .arc-image-section.arc-overlay
                            img.arc-img-cover src="https://plakatkunst.com/cdn/shop/files/50x50-traeramme-sort-smal.jpg?v=1697931537&width=2048"                        

app/views/blogs/layouts/_slider.html.slim
.arc-about.arc-section-spacing#arc-about
    .arc-container
        .arc-section-header
            h2.section-heading.arc-fs-xl About
            .section-description.arc-pt-4
                p orem ipsum dolor sit amet, consectetur adipiscing elit, sed 
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris 
                  nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat 
                  cupidatat non proident, sunt in culpa qui officia deserunt mollit 
                  anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor
                  incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
                  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 
                  consequat.
        .arc-designers-list
            .splide
                .splide__track
                    .arc-designer-card.arc-mt-6.arc-bg-white
                        ul.splide__list
                            li.splide__splide
                                .arc-image-section
                                    img.arc-img-cover src="https://www.w3schools.com/w3images/team2.jpg"
                                        .arc-card-content
                                            h3.arc-fs-xl.arc-pt-2 John Doe
                                            span.arc-pt-3 CEO & Founder
                                            p.arc-pt-3 Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                                            button.arc-btn-primary.arc-btn-fluid.arc-mt-3 Contact
            .splide
                .splide__track
                    .arc-designer-card.arc-mt-6.arc-bg-white
                        ul.splide__list
                            li.splide__splide
                                .arc-image-section
                                    img.arc-img-cover src="https://www.w3schools.com/w3images/team2.jpg"
                                        .arc-card-content
                                            h3.arc-fs-xl.arc-pt-2 John Doe
                                            span.arc-pt-3 CEO & Founder
                                            p.arc-pt-3 Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                                            button.arc-btn-primary.arc-btn-fluid.arc-mt-3 Contact
            .splide
                .splide__track
                    .arc-designer-card.arc-mt-6.arc-bg-white
                        ul.splide__list
                            li.splide__splide
                                .arc-image-section
                                    img.arc-img-cover src="https://www.w3schools.com/w3images/team2.jpg"
                                        .arc-card-content
                                            h3.arc-fs-xl.arc-pt-2 John Doe
                                            span.arc-pt-3 CEO & Founder
                                            p.arc-pt-3 Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                                            button.arc-btn-primary.arc-btn-fluid.arc-mt-3 Contact
            .splide
                .splide__track
                    .arc-designer-card.arc-mt-6.arc-bg-white
                        ul.splide__list
                            li.splide__splide
                                .arc-image-section
                                    img.arc-img-cover src="https://www.w3schools.com/w3images/team2.jpg"
                                        .arc-card-content
                                            h3.arc-fs-xl.arc-pt-2 John Doe
                                            span.arc-pt-3 CEO & Founder
                                            p.arc-pt-3 Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                                            button.arc-btn-primary.arc-btn-fluid.arc-mt-3 Contact                                                                                                
                
                 
                       

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Account</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application.tailwind" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= javascript_tag do %>
      const foo = '<%= select_tag(:foo, raw("<option>bar</option><option>baz</option>")) %>'
      $('#put_it_here').append(foo)
    <% end %>
  </head>

  <body>
      <%= yield %>
  </body>

  <script>
  $(document).ready(function () {
  // JS to smooth scroll div.
  $(".arc-menu a").on("click", function (e) {
    e.preventDefault();

    scrollTo($(this));
  });

  $(".arc-branding a").on("click", function (e) {
    e.preventDefault();

    scrollTo($(this));
  });

  function scrollTo(div) {
    var target = div.attr("href");
    var offset = 54.5;

    $("html, body").animate(
      {
        scrollTop: $(target).offset().top - offset,
      },
      800
    );
  }

  // Change background color on passing certain height.
  $(window).on("scroll", function () {
    var scrollHeight = 55;
    var div = $(".arc-header");

    if ($(window).scrollTop() > scrollHeight) {
      div.addClass("sticky-header");
    } else {
      div.removeClass("sticky-header");
    }
  });
});

new Splide(".splide", {
  type: "loop",
  perPage: 3,
  autoplay: "true",
  speed: 200,
  gap: "15px",
  breakpoints: {
    576: {
      perPage: 1,
    },
    768: {
      perPage: 2,
    },
  },
}).mount();

  </script>
</html>